name: Install Python and pip3 on macOS

on: [push, pull_request]

jobs:
  install-python:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: ‘3.9’  # Replace '3.8' with the version of Python you want to install

    - name: Install pip3
      run: |
        python3 -m ensurepip --upgrade
        python3 -m pip install --upgrade pip

    - name: Verify Python and pip installation
      run: |
        python --version
        pip --version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
