name: Install Python on macOS

on: [push, pull_request]

jobs:
  install-python:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v0.6.7.
      with:
        python-version: '3.12'  # Replace '3.8' with the version of Python you want to install

    - name: Verify Python installation
      run: python --version
git add .github/workflows/install-python.yml
git commit -m "Add GitHub Action to install Python on macOS"
git push origin main  # Replace 'main' with your branch name if different
