# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: "Push artifact to package repository"
      uses: cloudsmith-io/action@v0.5.4
      with:
        api-key: 2352304701e88ff1b8985f56614ebc2b9f4e87b2
        command: 'push'
        format: 'alpine'
        owner: test-org-IzW             # Your Cloudsmith account name or org name (namespace)
        repo: 'APITest'                                  # Your Cloudsmith Repository name (slug)
        distro: 'alpine'                                  # Your Distribution  (i.e debian, ubuntu, alpine)
        release: 'any-version'                            # Use "any-version" if your package is compatible with more than one version of alpine linux
        republish: 'true'                                 # Needed if version is not changing
        file: '${{steps.artifact.outputs.path}}'          # Package filename (including path)
        no-wait-for-sync: 'true'                          # Skip the waiting for package synchronisation (i.e. upload only)

